"""
Document builder — generates Word (.docx) and PDF files for resumes and cover letters.

Resume layout is hard-specced from Yang's actual PDFs. Haiku provides the tailored
text content; this module handles all formatting. Layout never changes.

Two resume templates:
  - Lending (Template A): black headings, horizontal rules between sections, bullet points
  - Risk/Controls (Template B): blue (#2E74B5) headings, name underline, dash bullets

Template is chosen automatically based on job type.
PDF is generated by converting the docx via python-docx + a simple HTML render fallback.
"""

import io
import os
import re
from pathlib import Path
from typing import Literal, Optional
import anthropic
from docx import Document
from docx.shared import Pt, RGBColor, Inches, Cm
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml.ns import qn
from docx.oxml import OxmlElement
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.units import cm as rl_cm
from reportlab.lib.colors import HexColor, black
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, HRFlowable
from config import CLAUDE_MODEL, CONTROL_RISK_SIGNALS

RL_BLUE = HexColor('#2E74B5')
RL_GREY = HexColor('#404040')

_client: Optional[anthropic.Anthropic] = None
_PROFILE_PATH = Path(__file__).parent / "data" / "candidate_profile.txt"
_RESUME_LENDING_PATH = Path(__file__).parent / "data" / "resume_general.txt"
_RESUME_RISK_PATH    = Path(__file__).parent / "data" / "resume_control_risk.txt"

BLUE = RGBColor(0x2E, 0x74, 0xB5)
BLACK = RGBColor(0x00, 0x00, 0x00)
DARK_GREY = RGBColor(0x40, 0x40, 0x40)


def _get_client() -> anthropic.Anthropic:
    global _client
    if _client is None:
        _client = anthropic.Anthropic(api_key=os.environ["ANTHROPIC_API_KEY"])
    return _client


def _load(path: Path) -> str:
    return path.read_text(encoding="utf-8") if path.exists() else ""


def _pick_template(job: dict) -> Literal["lending", "risk"]:
    combined = ((job.get("title") or "") + " " + (job.get("description") or "")).lower()
    for signal in CONTROL_RISK_SIGNALS:
        if signal.lower() in combined:
            return "risk"
    return "lending"


# ---------------------------------------------------------------------------
# Haiku — tailor resume content
# ---------------------------------------------------------------------------

_TAILOR_PROMPT = """\
You are tailoring Yang Yang's resume for a specific job. You must work ONLY with the
experience and skills already present in the base resume — never add anything new.

Rules:
- Rewrite the Professional Summary (2-3 short paragraphs) to directly address this role
- Rewrite the Core Skills list (10-12 skills max) to prioritise the most relevant ones
- Rewrite the experience bullets for each role to surface the most relevant points first,
  using the job's own language where it accurately reflects what Yang did
- Keep all employers, titles, dates, and education exactly as they are
- Never invent responsibilities, tools, certifications, or outcomes not in the original
- Output ONLY structured text in this exact format, nothing else:

SUMMARY
[paragraph 1]

[paragraph 2]

[paragraph 3 if needed]

SKILLS
[Skill 1]
[Skill 2]
[...up to 12]

ROLE: Bank of China Australia – Credit Risk Manager
[bullet 1]
[bullet 2]
[...all bullets]

ROLE: Bank of China Australia – Assistant Relationship Manager
[bullet 1]
[...]

ROLE: Bank of China Australia – Teller
[bullet 1]
[...]

Candidate profile: {profile}

Job title: {title}
Company: {company}
Job description: {description}

Base resume:
{resume}"""


def _tailor_content(job: dict, template: str) -> dict:
    """Call Haiku to tailor resume content. Returns parsed sections dict."""
    client = _get_client()
    profile = _load(_PROFILE_PATH)
    resume  = _load(_RESUME_RISK_PATH if template == "risk" else _RESUME_LENDING_PATH)

    resp = client.messages.create(
        model=CLAUDE_MODEL,
        max_tokens=2000,
        messages=[{
            "role": "user",
            "content": _TAILOR_PROMPT.format(
                profile=profile[:2500],
                title=job.get("title", ""),
                company=job.get("company", ""),
                description=(job.get("description") or "")[:2000],
                resume=resume,
            ),
        }],
    )
    return _parse_tailored(resp.content[0].text.strip())


def _parse_tailored(text: str) -> dict:
    """Parse Haiku's structured output into sections."""
    sections = {"summary": [], "skills": [], "roles": {}}
    current = None
    current_role = None
    lines = text.splitlines()

    for line in lines:
        stripped = line.strip()
        if stripped == "SUMMARY":
            current = "summary"
        elif stripped == "SKILLS":
            current = "skills"
        elif stripped.startswith("ROLE:"):
            current = "role"
            current_role = stripped[5:].strip()
            sections["roles"][current_role] = []
        elif current == "summary" and stripped:
            sections["summary"].append(stripped)
        elif current == "skills" and stripped:
            sections["skills"].append(stripped)
        elif current == "role" and current_role and stripped:
            # Strip leading dash or bullet
            bullet = re.sub(r'^[-•]\s*', '', stripped)
            if bullet:
                sections["roles"][current_role].append(bullet)

    return sections


# ---------------------------------------------------------------------------
# Word document builder
# ---------------------------------------------------------------------------

def _add_horizontal_rule(doc: Document) -> None:
    """Add a thin full-width horizontal line."""
    p = doc.add_paragraph()
    p.paragraph_format.space_before = Pt(2)
    p.paragraph_format.space_after = Pt(2)
    pPr = p._p.get_or_add_pPr()
    pBdr = OxmlElement('w:pBdr')
    bottom = OxmlElement('w:bottom')
    bottom.set(qn('w:val'), 'single')
    bottom.set(qn('w:sz'), '6')
    bottom.set(qn('w:space'), '1')
    bottom.set(qn('w:color'), 'auto')
    pBdr.append(bottom)
    pPr.append(pBdr)


def _set_font(run, size_pt: float, bold: bool = False,
              color: RGBColor = BLACK, name: str = "Calibri") -> None:
    run.font.name = name
    run.font.size = Pt(size_pt)
    run.font.bold = bold
    run.font.color.rgb = color


def _section_heading(doc: Document, text: str, template: str) -> None:
    p = doc.add_paragraph()
    p.paragraph_format.space_before = Pt(8)
    p.paragraph_format.space_after = Pt(2)
    run = p.add_run(text)
    color = BLUE if template == "risk" else BLACK
    _set_font(run, 11, bold=True, color=color)


def build_resume_docx(job: dict) -> bytes:
    """Build a tailored resume Word document. Returns bytes."""
    template = _pick_template(job)
    content  = _tailor_content(job, template)

    doc = Document()

    # Page margins
    for section in doc.sections:
        section.top_margin    = Cm(2.0)
        section.bottom_margin = Cm(2.0)
        section.left_margin   = Cm(2.54)
        section.right_margin  = Cm(2.54)

    # Remove default paragraph spacing
    style = doc.styles['Normal']
    style.font.name = "Calibri"
    style.font.size = Pt(11)
    style.paragraph_format.space_after = Pt(0)

    # --- Name ---
    name_para = doc.add_paragraph()
    name_para.paragraph_format.space_after = Pt(2)
    name_run = name_para.add_run("Yang Yang")
    _set_font(name_run, 20, bold=True)

    if template == "risk":
        # Blue underline rule directly under name
        _add_horizontal_rule(doc)

    # --- Contact ---
    contact_para = doc.add_paragraph()
    contact_para.paragraph_format.space_after = Pt(2)
    c1 = contact_para.add_run("Sydney NSW | Australian Permanent Resident")
    _set_font(c1, 10, color=DARK_GREY)

    contact_para2 = doc.add_paragraph()
    contact_para2.paragraph_format.space_after = Pt(6)
    c2 = contact_para2.add_run("0401 877 625 | yy.lu.33@gmail.com")
    _set_font(c2, 10, color=DARK_GREY)

    if template == "lending":
        _add_horizontal_rule(doc)

    # --- Professional Summary ---
    _section_heading(doc, "Professional Summary", template)
    for para_text in content["summary"]:
        p = doc.add_paragraph()
        p.paragraph_format.space_after = Pt(4)
        run = p.add_run(para_text)
        _set_font(run, 11)

    if template == "lending":
        _add_horizontal_rule(doc)

    # --- Core Skills ---
    _section_heading(doc, "Core Skills", template)
    for skill in content["skills"]:
        p = doc.add_paragraph()
        p.paragraph_format.space_after = Pt(1)
        run = p.add_run(skill)
        _set_font(run, 11)

    if template == "lending":
        _add_horizontal_rule(doc)

    # --- Professional Experience ---
    _section_heading(doc, "Professional Experience", template)

    roles_order = [
        ("Bank of China Australia – Credit Risk Manager",        "Sydney Head Office | 2019 – 2023"),
        ("Bank of China Australia – Assistant Relationship Manager", "Hurstville Branch | 2016 – 2019"),
        ("Bank of China Australia – Teller",                     "Hurstville Branch | 2013 – 2015"),
    ]

    for role_name, role_meta in roles_order:
        # Role title (bold)
        p = doc.add_paragraph()
        p.paragraph_format.space_before = Pt(6)
        p.paragraph_format.space_after = Pt(1)
        run = p.add_run(role_name)
        _set_font(run, 11, bold=True)

        # Role meta (location | dates)
        p2 = doc.add_paragraph()
        p2.paragraph_format.space_after = Pt(3)
        run2 = p2.add_run(role_meta)
        _set_font(run2, 11, color=DARK_GREY)

        # Find matching bullets
        bullets = []
        for key, items in content["roles"].items():
            if role_name.lower()[:20] in key.lower():
                bullets = items
                break

        for bullet_text in bullets:
            p3 = doc.add_paragraph(style='List Bullet' if template == "lending" else 'Normal')
            p3.paragraph_format.space_after = Pt(2)
            p3.paragraph_format.left_indent = Inches(0.25)
            if template == "risk":
                run3 = p3.add_run(f"– {bullet_text}")
            else:
                run3 = p3.add_run(bullet_text)
            _set_font(run3, 11)

        if template == "lending":
            _add_horizontal_rule(doc)

    # --- Education ---
    _section_heading(doc, "Education", template)
    for line in ["Master of Finance – Western Sydney University",
                 "Bachelor of Accounting – Southern Cross University"]:
        p = doc.add_paragraph()
        p.paragraph_format.space_after = Pt(2)
        run = p.add_run(line)
        _set_font(run, 11)

    # Save to bytes
    buf = io.BytesIO()
    doc.save(buf)
    buf.seek(0)
    return buf.read()


def build_cover_letter_docx(text: str) -> bytes:
    """Wrap cover letter text in a simple Word document."""
    doc = Document()
    for section in doc.sections:
        section.top_margin    = Cm(2.54)
        section.bottom_margin = Cm(2.54)
        section.left_margin   = Cm(2.54)
        section.right_margin  = Cm(2.54)

    style = doc.styles['Normal']
    style.font.name = "Calibri"
    style.font.size = Pt(11)
    style.paragraph_format.space_after = Pt(0)

    for line in text.splitlines():
        p = doc.add_paragraph()
        p.paragraph_format.space_after = Pt(6)
        run = p.add_run(line)
        run.font.name = "Calibri"
        run.font.size = Pt(11)

    buf = io.BytesIO()
    doc.save(buf)
    buf.seek(0)
    return buf.read()


def _rl_style(name: str, **kw) -> ParagraphStyle:
    return ParagraphStyle(name, **kw)


def build_resume_pdf(job: dict) -> bytes:
    """Generate a PDF resume using reportlab — works on Streamlit Cloud."""
    template = _pick_template(job)
    content  = _tailor_content(job, template)
    head_color = RL_BLUE if template == "risk" else black

    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4,
                            topMargin=2*rl_cm, bottomMargin=2*rl_cm,
                            leftMargin=2.54*rl_cm, rightMargin=2.54*rl_cm)

    name_s    = _rl_style("Name",    fontName="Helvetica-Bold", fontSize=20, spaceAfter=3)
    contact_s = _rl_style("Contact", fontName="Helvetica",      fontSize=10, textColor=RL_GREY, spaceAfter=2)
    head_s    = _rl_style("Head",    fontName="Helvetica-Bold", fontSize=11, textColor=head_color, spaceBefore=10, spaceAfter=3)
    body_s    = _rl_style("Body",    fontName="Helvetica",      fontSize=11, spaceAfter=3, leading=14)
    bullet_s  = _rl_style("Bullet",  fontName="Helvetica",      fontSize=11, spaceAfter=2, leading=14, leftIndent=12)
    role_s    = _rl_style("Role",    fontName="Helvetica-Bold", fontSize=11, spaceBefore=8, spaceAfter=2)
    meta_s    = _rl_style("Meta",    fontName="Helvetica",      fontSize=11, textColor=RL_GREY, spaceAfter=3)

    def hr(color=black):
        return HRFlowable(width="100%", thickness=0.5, color=color, spaceBefore=4, spaceAfter=4)

    story = []
    story.append(Paragraph("Yang Yang", name_s))
    if template == "risk":
        story.append(hr(RL_BLUE))
    story.append(Paragraph("Sydney NSW | Australian Permanent Resident", contact_s))
    story.append(Paragraph("0401 877 625 | yy.lu.33@gmail.com", contact_s))
    story.append(Spacer(1, 4))
    if template == "lending":
        story.append(hr())

    story.append(Paragraph("Professional Summary", head_s))
    for p in content["summary"]:
        story.append(Paragraph(p, body_s))
    if template == "lending":
        story.append(hr())

    story.append(Paragraph("Core Skills", head_s))
    for skill in content["skills"]:
        story.append(Paragraph(skill, body_s))
    if template == "lending":
        story.append(hr())

    story.append(Paragraph("Professional Experience", head_s))
    roles_order = [
        ("Bank of China Australia – Credit Risk Manager",           "Sydney Head Office | 2019 – 2023"),
        ("Bank of China Australia – Assistant Relationship Manager", "Hurstville Branch | 2016 – 2019"),
        ("Bank of China Australia – Teller",                        "Hurstville Branch | 2013 – 2015"),
    ]
    for role_name, role_meta in roles_order:
        story.append(Paragraph(role_name, role_s))
        story.append(Paragraph(role_meta, meta_s))
        bullets = []
        for key, items in content["roles"].items():
            if role_name.lower()[:20] in key.lower():
                bullets = items
                break
        prefix = "–" if template == "risk" else "•"
        for bt in bullets:
            story.append(Paragraph(f"{prefix} {bt}", bullet_s))
        if template == "lending":
            story.append(hr())

    story.append(Paragraph("Education", head_s))
    story.append(Paragraph("Master of Finance – Western Sydney University", body_s))
    story.append(Paragraph("Bachelor of Accounting – Southern Cross University", body_s))

    doc.build(story)
    buf.seek(0)
    return buf.read()


def build_cover_letter_pdf(text: str) -> bytes:
    """Generate a PDF cover letter using reportlab."""
    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4,
                            topMargin=2.54*rl_cm, bottomMargin=2.54*rl_cm,
                            leftMargin=2.54*rl_cm, rightMargin=2.54*rl_cm)
    body_s = _rl_style("CLBody", fontName="Helvetica", fontSize=11, leading=16, spaceAfter=8)
    story  = []
    for line in text.splitlines():
        if line.strip():
            story.append(Paragraph(line.strip(), body_s))
        else:
            story.append(Spacer(1, 8))
    doc.build(story)
    buf.seek(0)
    return buf.read()
