"""
Document builder — generates Word (.docx) and PDF files for resumes and cover letters.

Resume layout is hard-specced from Yang's actual PDFs. Haiku provides the tailored
text content; this module handles all formatting. Layout never changes.

Two resume templates:
  - Lending (Template A): black headings, horizontal rules between sections, bullet points
  - Risk/Controls (Template B): blue (#2E74B5) headings, name underline, dash bullets

Template is chosen automatically based on job type.
PDF is generated by converting the docx via python-docx + a simple HTML render fallback.
"""

import io
import os
import re
from pathlib import Path
from typing import Literal, Optional
import anthropic
from docx import Document
from docx.shared import Pt, RGBColor, Inches, Cm
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml.ns import qn
from docx.oxml import OxmlElement
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.units import cm as rl_cm
from reportlab.lib.colors import HexColor, black
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, HRFlowable, Table, TableStyle
from config import CLAUDE_MODEL, CONTROL_RISK_SIGNALS

RL_BLUE = HexColor('#2E74B5')
RL_GREY = HexColor('#404040')

_client: Optional[anthropic.Anthropic] = None
_PROFILE_PATH = Path(__file__).parent / "data" / "candidate_profile.txt"
_RESUME_LENDING_PATH = Path(__file__).parent / "data" / "resume_general.txt"
_RESUME_RISK_PATH    = Path(__file__).parent / "data" / "resume_control_risk.txt"

BLUE = RGBColor(0x2E, 0x74, 0xB5)
BLACK = RGBColor(0x00, 0x00, 0x00)
DARK_GREY = RGBColor(0x40, 0x40, 0x40)


def _get_client() -> anthropic.Anthropic:
    global _client
    if _client is None:
        _client = anthropic.Anthropic(api_key=os.environ["ANTHROPIC_API_KEY"])
    return _client


def _load(path: Path) -> str:
    return path.read_text(encoding="utf-8") if path.exists() else ""


def _pick_template(job: dict) -> Literal["lending", "risk"]:
    combined = ((job.get("title") or "") + " " + (job.get("description") or "")).lower()
    for signal in CONTROL_RISK_SIGNALS:
        if signal.lower() in combined:
            return "risk"
    return "lending"


# ---------------------------------------------------------------------------
# Haiku — tailor resume content
# ---------------------------------------------------------------------------

_TAILOR_PROMPT = """\
You are tailoring Yang Yang's resume for a specific job. You must work ONLY with the
experience and skills already present in the base resume — never add anything new.

Rules:
- Rewrite the Professional Summary as ONE tight paragraph, 3-4 sentences maximum.
  Do not use multiple paragraphs. Be direct and specific to this role.
- Rewrite the Core Skills list (10-12 skills max) to prioritise the most relevant ones.
  Write each skill as a short phrase only — no dashes or bullets, just the phrase.
- Rewrite the experience bullets for each role to surface the most relevant points first,
  using the job's own language where it accurately reflects what Yang did.
- Keep each bullet to ONE concise line — strictly under 100 characters. Cut any bullet
  that cannot be made concise without losing meaning.
- Keep all employers, titles, dates, and education exactly as they are.
- Never invent responsibilities, tools, certifications, or outcomes not in the original.
- Output ONLY structured text in this exact format, nothing else:

SUMMARY
[single paragraph, 3-4 sentences]

SKILLS
[Skill 1]
[Skill 2]
[...up to 12]

ROLE: Bank of China Australia – Credit Risk Manager
[bullet 1]
[bullet 2]
[...all bullets]

ROLE: Bank of China Australia – Assistant Relationship Manager
[bullet 1]
[...]

ROLE: Bank of China Australia – Teller
[bullet 1]
[...]

Candidate profile: {profile}

Job title: {title}
Company: {company}
Job description: {description}

Base resume:
{resume}"""


def _tailor_content(job: dict, template: str) -> dict:
    """Call Haiku to tailor resume content. Returns parsed sections dict."""
    client = _get_client()
    profile = _load(_PROFILE_PATH)
    resume  = _load(_RESUME_RISK_PATH if template == "risk" else _RESUME_LENDING_PATH)

    resp = client.messages.create(
        model=CLAUDE_MODEL,
        max_tokens=2000,
        messages=[{
            "role": "user",
            "content": _TAILOR_PROMPT.format(
                profile=profile[:2500],
                title=job.get("title", ""),
                company=job.get("company", ""),
                description=(job.get("description") or "")[:2000],
                resume=resume,
            ),
        }],
    )
    return _parse_tailored(resp.content[0].text.strip())


def _parse_tailored(text: str) -> dict:
    """Parse Haiku's structured output into sections."""
    sections = {"summary": [], "skills": [], "roles": {}}
    current = None
    current_role = None
    lines = text.splitlines()

    for line in lines:
        stripped = line.strip()
        if stripped == "SUMMARY":
            current = "summary"
        elif stripped == "SKILLS":
            current = "skills"
        elif stripped.startswith("ROLE:"):
            current = "role"
            current_role = stripped[5:].strip()
            sections["roles"][current_role] = []
        elif current == "summary" and stripped:
            sections["summary"].append(stripped)
        elif current == "skills" and stripped:
            # Strip any leading dash/bullet Haiku sometimes adds
            skill = re.sub(r'^[-•]\s*', '', stripped)
            if skill:
                sections["skills"].append(skill)
        elif current == "role" and current_role and stripped:
            # Strip leading dash or bullet
            bullet = re.sub(r'^[-•–]\s*', '', stripped)
            # Skip lines that look like location/date metadata e.g. "Sydney | 2019 – 2023"
            if bullet and not re.search(r'\|\s*\d{4}', bullet):
                sections["roles"][current_role].append(bullet)

    return sections


# ---------------------------------------------------------------------------
# Role-bullet matching helper
# ---------------------------------------------------------------------------

def _find_role_bullets(role_name: str, roles_dict: dict) -> list:
    """Return bullets for role_name from the parsed roles dict.

    Matches on the job-title portion after '–' so that roles sharing the
    same employer prefix ('Bank of China Australia') don't all resolve to
    the same entry.  Falls back to a full-name substring match.
    """
    def title_part(name: str) -> str:
        parts = name.split("–")
        return parts[-1].strip().lower() if len(parts) > 1 else name.lower()

    target = title_part(role_name)
    # Pass 1: match on title portion
    for key, items in roles_dict.items():
        if target[:18] in title_part(key) or title_part(key)[:18] in target:
            return items
    # Pass 2: fallback full-name substring
    for key, items in roles_dict.items():
        if role_name.lower()[:30] in key.lower():
            return items
    return []


# ---------------------------------------------------------------------------
# Word document builder
# ---------------------------------------------------------------------------

def _add_horizontal_rule(doc: Document) -> None:
    """Add a thin full-width horizontal line."""
    p = doc.add_paragraph()
    p.paragraph_format.space_before = Pt(2)
    p.paragraph_format.space_after = Pt(2)
    pPr = p._p.get_or_add_pPr()
    pBdr = OxmlElement('w:pBdr')
    bottom = OxmlElement('w:bottom')
    bottom.set(qn('w:val'), 'single')
    bottom.set(qn('w:sz'), '6')
    bottom.set(qn('w:space'), '1')
    bottom.set(qn('w:color'), 'auto')
    pBdr.append(bottom)
    pPr.append(pBdr)


def _set_font(run, size_pt: float, bold: bool = False,
              color: RGBColor = BLACK, name: str = "Calibri") -> None:
    run.font.name = name
    run.font.size = Pt(size_pt)
    run.font.bold = bold
    run.font.color.rgb = color


def _section_heading(doc: Document, text: str, template: str) -> None:
    p = doc.add_paragraph()
    p.paragraph_format.space_before = Pt(6)
    p.paragraph_format.space_after = Pt(2)
    run = p.add_run(text)
    color = BLUE if template == "risk" else BLACK
    _set_font(run, 10.5, bold=True, color=color)


def build_resume_docx(job: dict) -> bytes:
    """Build a tailored resume Word document. Returns bytes."""
    template = _pick_template(job)
    content  = _tailor_content(job, template)

    doc = Document()

    # Tighter margins
    for section in doc.sections:
        section.top_margin    = Cm(1.8)
        section.bottom_margin = Cm(1.8)
        section.left_margin   = Cm(2.2)
        section.right_margin  = Cm(2.2)

    style = doc.styles['Normal']
    style.font.name = "Calibri"
    style.font.size = Pt(10)
    style.paragraph_format.space_after = Pt(0)

    # --- Name ---
    name_para = doc.add_paragraph()
    name_para.paragraph_format.space_after = Pt(1)
    name_run = name_para.add_run("Yang Yang")
    _set_font(name_run, 18, bold=True)

    if template == "risk":
        _add_horizontal_rule(doc)

    # --- Contact (single line) ---
    contact_para = doc.add_paragraph()
    contact_para.paragraph_format.space_after = Pt(5)
    c = contact_para.add_run(
        "Sydney NSW  |  Australian Permanent Resident  |  0401 877 625  |  yy.lu.33@gmail.com"
    )
    _set_font(c, 9.5, color=DARK_GREY)

    if template == "lending":
        _add_horizontal_rule(doc)

    # --- Professional Summary ---
    _section_heading(doc, "Professional Summary", template)
    # Summary is now a single paragraph from Haiku
    summary_text = " ".join(content["summary"])
    p = doc.add_paragraph()
    p.paragraph_format.space_after = Pt(3)
    run = p.add_run(summary_text)
    _set_font(run, 10)

    if template == "lending":
        _add_horizontal_rule(doc)

    # --- Core Skills (inline, pipe-separated) ---
    _section_heading(doc, "Core Skills", template)
    skills_line = "  ·  ".join(content["skills"])
    p = doc.add_paragraph()
    p.paragraph_format.space_after = Pt(3)
    run = p.add_run(skills_line)
    _set_font(run, 10)

    if template == "lending":
        _add_horizontal_rule(doc)

    # --- Professional Experience ---
    _section_heading(doc, "Professional Experience", template)

    roles_order = [
        ("Bank of China Australia – Credit Risk Manager",        "Sydney Head Office | 2019 – 2023"),
        ("Bank of China Australia – Assistant Relationship Manager", "Hurstville Branch | 2016 – 2019"),
        ("Bank of China Australia – Teller",                     "Hurstville Branch | 2013 – 2015"),
    ]

    for role_name, role_meta in roles_order:
        p = doc.add_paragraph()
        p.paragraph_format.space_before = Pt(5)
        p.paragraph_format.space_after = Pt(1)
        run = p.add_run(role_name)
        _set_font(run, 10.5, bold=True)

        p2 = doc.add_paragraph()
        p2.paragraph_format.space_after = Pt(2)
        run2 = p2.add_run(role_meta)
        _set_font(run2, 9.5, color=DARK_GREY)

        bullets = _find_role_bullets(role_name, content["roles"])
        for bullet_text in bullets:
            p3 = doc.add_paragraph(style='List Bullet' if template == "lending" else 'Normal')
            p3.paragraph_format.space_after = Pt(1)
            p3.paragraph_format.left_indent   = Inches(0.2)
            p3.paragraph_format.first_line_indent = Inches(-0.2)
            if template == "risk":
                run3 = p3.add_run(f"– {bullet_text}")
            else:
                run3 = p3.add_run(bullet_text)
            _set_font(run3, 10)

        if template == "lending":
            _add_horizontal_rule(doc)

    # --- Education ---
    _section_heading(doc, "Education", template)
    for line in ["Master of Finance – Western Sydney University",
                 "Bachelor of Accounting – Southern Cross University"]:
        p = doc.add_paragraph()
        p.paragraph_format.space_after = Pt(1)
        run = p.add_run(line)
        _set_font(run, 10)

    buf = io.BytesIO()
    doc.save(buf)
    buf.seek(0)
    return buf.read()


def build_cover_letter_docx(text: str) -> bytes:
    """Wrap cover letter text in a simple Word document."""
    doc = Document()
    for section in doc.sections:
        section.top_margin    = Cm(2.54)
        section.bottom_margin = Cm(2.54)
        section.left_margin   = Cm(2.54)
        section.right_margin  = Cm(2.54)

    style = doc.styles['Normal']
    style.font.name = "Calibri"
    style.font.size = Pt(11)
    style.paragraph_format.space_after = Pt(0)

    for line in text.splitlines():
        p = doc.add_paragraph()
        p.paragraph_format.space_after = Pt(6)
        run = p.add_run(line)
        run.font.name = "Calibri"
        run.font.size = Pt(11)

    buf = io.BytesIO()
    doc.save(buf)
    buf.seek(0)
    return buf.read()


def _rl_style(name: str, **kw) -> ParagraphStyle:
    return ParagraphStyle(name, **kw)


def build_resume_pdf(job: dict) -> bytes:
    """Generate a PDF resume using reportlab — works on Streamlit Cloud."""
    template = _pick_template(job)
    content  = _tailor_content(job, template)
    head_color = RL_BLUE if template == "risk" else black

    buf = io.BytesIO()
    # Tighter margins — more breathing room for content
    doc = SimpleDocTemplate(buf, pagesize=A4,
                            topMargin=1.8*rl_cm, bottomMargin=1.8*rl_cm,
                            leftMargin=2.0*rl_cm,  rightMargin=2.0*rl_cm)

    # Compact type scale
    name_s    = _rl_style("Name",    fontName="Helvetica-Bold", fontSize=18, spaceAfter=2)
    contact_s = _rl_style("Contact", fontName="Helvetica",      fontSize=9.5, textColor=RL_GREY, spaceAfter=4)
    head_s    = _rl_style("Head",    fontName="Helvetica-Bold", fontSize=10.5,
                          textColor=head_color, spaceBefore=7, spaceAfter=2)
    body_s    = _rl_style("Body",    fontName="Helvetica",      fontSize=10, spaceAfter=2, leading=12)
    # Hanging indent: dash sits at left edge, wrapped text indents past it
    bullet_s  = _rl_style("Bullet",  fontName="Helvetica",      fontSize=10, spaceAfter=1,
                          leading=12, leftIndent=14, firstLineIndent=-14)
    role_s    = _rl_style("Role",    fontName="Helvetica-Bold", fontSize=10.5, spaceBefore=6, spaceAfter=1)
    meta_s    = _rl_style("Meta",    fontName="Helvetica",      fontSize=9.5, textColor=RL_GREY, spaceAfter=2)

    def hr(color=black):
        return HRFlowable(width="100%", thickness=0.5, color=color, spaceBefore=2, spaceAfter=2)

    story = []

    # Name + contact
    story.append(Paragraph("Yang Yang", name_s))
    if template == "risk":
        story.append(hr(RL_BLUE))
    story.append(Paragraph(
        "Sydney NSW  |  Australian Permanent Resident  |  0401 877 625  |  yy.lu.33@gmail.com",
        contact_s,
    ))
    if template == "lending":
        story.append(hr())

    # Professional Summary — single paragraph
    story.append(Paragraph("Professional Summary", head_s))
    summary_text = " ".join(content["summary"])
    story.append(Paragraph(summary_text, body_s))
    if template == "lending":
        story.append(hr())

    # Core Skills — inline, separated by · to avoid column-wrapping mess
    story.append(Paragraph("Core Skills", head_s))
    skills_line = "  ·  ".join(content["skills"])
    story.append(Paragraph(skills_line, body_s))
    if template == "lending":
        story.append(hr())

    # Professional Experience
    story.append(Paragraph("Professional Experience", head_s))
    roles_order = [
        ("Bank of China Australia – Credit Risk Manager",           "Sydney Head Office | 2019 – 2023"),
        ("Bank of China Australia – Assistant Relationship Manager", "Hurstville Branch | 2016 – 2019"),
        ("Bank of China Australia – Teller",                        "Hurstville Branch | 2013 – 2015"),
    ]
    bullet_prefix = "–" if template == "risk" else "•"
    for role_name, role_meta in roles_order:
        story.append(Paragraph(role_name, role_s))
        story.append(Paragraph(role_meta, meta_s))
        for bt in _find_role_bullets(role_name, content["roles"]):
            story.append(Paragraph(f"{bullet_prefix}  {bt}", bullet_s))
        if template == "lending":
            story.append(hr())

    # Education
    story.append(Paragraph("Education", head_s))
    story.append(Paragraph("Master of Finance – Western Sydney University", body_s))
    story.append(Paragraph("Bachelor of Accounting – Southern Cross University", body_s))

    doc.build(story)
    buf.seek(0)
    return buf.read()


def build_cover_letter_pdf(text: str) -> bytes:
    """Generate a PDF cover letter using reportlab."""
    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4,
                            topMargin=2.54*rl_cm, bottomMargin=2.54*rl_cm,
                            leftMargin=2.54*rl_cm, rightMargin=2.54*rl_cm)
    body_s = _rl_style("CLBody", fontName="Helvetica", fontSize=11, leading=16, spaceAfter=8)
    story  = []
    for line in text.splitlines():
        if line.strip():
            story.append(Paragraph(line.strip(), body_s))
        else:
            story.append(Spacer(1, 8))
    doc.build(story)
    buf.seek(0)
    return buf.read()
